source 'https://rubygems.org'

gem 'eventmachine'
gem 'colorize'
gem 'rspec'
gem 'rspec-mocks'
gem 'facets'
gem 'pry'
gem 'pry-remote'
gem 'pry-rescue'
gem 'pry-stack_explorer'
gem 'malloc_trim'
gem 'memory_profiler'
gem 'get_process_mem'
